#USE THE OFFICIAL UBUNTU IMAGE AS THE BASE IAMGE
FROM ubuntu
#UPDATE THE PACKAGE LIST AND INSTALL APACHE2
RUN apt-get update -y && \
apt-get install apache2 -y
#COPY THE INDEX>HTML FILE TO THE APACHE ROOT DIRECTORY
COPY index.html /var/www/html/
#START THE APACHE@ SERVICE IN THE FOREGROUND
CMD ["usr/sbin/apachectl","-D","FOREGROUND"]
